### ISSUE TITLE
Some packages' version  are too old 

### ISSUE THREAD

**Issue by qy1026** [uclaml/SPPO#7]
When use `accelerate==0.23.0` in `setup.py`, it got the following error:
`Accelerator.__init__() got an unexpected keyword argument use_seedable_sampler`
When upgrade `accelerate` to 0.31.0, this error fixed.
